global_options:
  dart_mappable_builder:
    options:
      runs_before:
      - retrofit_generator
      renameMethods:
        fromJson: fromJsonString
        toJson: toJsonString
        fromMap: fromJson
        toMap: toJson